config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

    namespace :admin do
      root to: 'homes#top'
      resources :items, only: [:index, :new, :create, :update, :edit, :show]
      resources :customers, only: [:index, :show, :edit, :update]
      resources :orders, only: [:show, :update]
      resources :order_items, only: [:update]
    end

    scope module: :public do
      root to: 'homes#top'
      get 'home/about', to: 'homes#about', as: :about

      get 'customers/my_page', to: 'customers#show', as: :my_page
      get 'customers/information/edit',to: 'customers#edit', as: :edit
      patch 'customers/information', to: 'customers#update'
      get 'customers/confirm_withdraw', to: 'customers#confirm_withdraw', as: :confirm_withdraw
      patch 'customer/withdraw', to: 'customers#withdraw'

      resources :items, only: [:index, :show]
      resources :addresses, only: [:index, :create, :update, :destroy, :edit]
      resources :cart_items, only: [:create, :index, :update, :destroy]
      delete '/cart_items', to: 'cart_items#destroy_all'
      get '/orders/complete', to: 'orders#complete'
      resources :orders, only: [:new, :index, :show]
      post 'orders/confirm_order', to: 'orders#confirm_order', as: :confirm_order
      post '/orders', to: 'orders#create'
    end




# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def active_for_authentication?
      super && (self.is_active == false)
  end
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + last_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
    
  end
  
  
  
  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :email, :telephone_number, :is_active)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mb-5 pt-5">
    <div class="col-xs-10 col-xs-offset-1">
  <h2>会員情報編集</h2>

  <%= form_for(@customer, url: admin_customer_path) do |f| %>

  <table class="row table">
    <tr>
      <th class="col-xs-2"><%= f.label :会員ID %></th>
      <td class="col-xs-10"><%= f.text_field :id  , class:"form-control"%></td>
    </tr>

    <tr>
      <th><%= f.label :氏名 %></th>
      <td><%= f.text_field :last_name, class:"form-control" %><br>
          <%= f.text_field :first_name, class:"form-control" %>
      </td>
    </tr>

    <tr>
      <th><%= f.label :フリガナ %></th>
      <td><%= f.text_field :last_name_kana, class:"form-control" %><br>
      <%= f.text_field :first_name_kana, class:"form-control" %>
      </td>
    </tr>

    <tr>
      <th><%= f.label :郵便番号 %></th>
      <td><%= f.text_field :postal_code, class:"form-control" %></td>
    </tr>

    <tr>
      <th><%= f.label :住所 %></th>
      <td><%= f.text_field :address, class:"form-control" %></td>
    </tr>

    <tr>
      <th><%= f.label :電話番号 %></th>
      <td><%= f.text_field :telephone_number, class:"form-control" %></td>
    </tr>

    <tr>
      <th><%= f.label :メールアドレス %></th>
      <td><%= f.text_field :email , class:"form-control"%></td>
    </tr>
      <th>会員ステータス</th>
      <td>
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active,"有効", {value: :true, style: "display: inline-block;"} %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "退会", {value: :false, style: "display: inline-block;"} %>
      </td>
    <tr>
      <th></th>
      <td>
        <%= f.submit '変更を保存', class: "btn btn-success" %></td>
    </tr>
    <% end %>
  </table>
  
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h5><strong>会員一覧</strong></h5>
  <div class="d-flex justify-content-center" %>
    <table class="mt-5 table">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer) do %>
              <%= customer.last_name + customer.first_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_active == true %>
            有効
            <% else %>
            退会
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @customers, class: "mt-2" %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h5><strong>
    <%= @customer.last_name + @customer.first_name %>
  </strong>さんの
  <strong>会員詳細</strong></h5>
  
  <table class="mt-5 table table-borderless">
    <tr>
      <th>会員ID</th>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <th>氏名</th>
      <td><%= @customer.last_name %> <%= @customer.first_name %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <th>会員ステータス</th>
      <td>
        <% if @customer.is_active == true %>
        有効
        <% else %>
        退会
        <% end %>
      </td>
    </tr>
    <tr>
      <th></th>
      <td>
        <%= link_to '編集する', edit_admin_customer_path(@customer), class: "mr-5 btn btn-success" %><span>
          <%= link_to '注文履歴一覧を見る', admin_order_path, class: "btn btn-primary" %>
        </span>
      </td>
    </tr>
  </table>
  
</div>